/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-126242-geb0bfa852e-20260822"
#endif /* AVUTIL_FFVERSION_H */
